# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_01
  pid: {p: 100, i: 0.01, d: 1}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01__link_02
  pid: {p: 100, i: 0.01, d: 1}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02__link_03
  pid: {p: 100, i: 0.01, d: 1}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03__link_04
  pid: {p: 100, i: 0.01, d: 1}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04__link_05
  pid: {p: 100, i: 0.01, d: 1}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_05__link_06
  pid: {p: 100, i: 0.01, d: 1}
joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: left_joint
  pid: {p: 0.05.0, i: 0, d: 0} 
joint8_position_controller:
  type: position_controllers/JointPositionController
  joint: right_joint
  pid: {p: 0.05, i: 0, d: 0 }

